init

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,63 +1,46 @@
----
-###########################
-###########################
-## Linter GitHub Actions ##
-###########################
-###########################
-name: Lint Code Base
+name: Build Check
 
-#
-# Documentation:
-# https://help.github.com/en/articles/workflow-syntax-for-github-actions
-#
-
-#############################
-# Start the job on all push #
-#############################
 on:
   push:
-    branches: [master]
-    # Remove the line above to run when pushing to master
+    branches:
+      - main
+      - master
   pull_request:
-    branches: [master]
+    branches:
+      - main
+      - master
 
-###############
-# Set the Job #
-###############
 jobs:
   build:
-    # Name the Job
-    name: Lint Code Base
-    # Set the agent to run on
     runs-on: ubuntu-latest
 
-    ##################
-    # Load all steps #
-    ##################
     steps:
-      ##########################
-      # Checkout the code base #
-      ##########################
-      - name: Checkout Code
-        uses: actions/checkout@v2
-        with:
-          # Full git history is needed to get a proper list of changed files within `super-linter`
-          fetch-depth: 0
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      ################################
-      # Run Linter against code base #
-      ################################
-      - name: Lint Code Base
-        uses: github/super-linter@v4
-        env:
-          VALIDATE_ALL_CODEBASE: true
-          VALIDATE_MARKDOWN: false
-          VALIDATE_NATURAL_LANGUAGE: false
-          VALIDATE_YAML: false
-          DEFAULT_BRANCH: master
-          VALIDATE_DOCKERFILE: false
-          VALIDATE_DOCKERFILE_HADOLINT: false
-          VALIDATE_PYTHON_FLAKE8: false
-          VALIDATE_BASH: false
-          VALIDATE_JSCPD: false
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: Setup Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '20.1'
+
+    - name: Install pnpm
+      run: npm install -g pnpm
+
+    - name: Install dependencies
+      run: |
+        cd devsoc24-landing
+        pnpm install
+
+    - name: Build project
+      run: |
+        cd devsoc24-landing
+        pnpm run build
+
+    - name: Check for build errors
+      run: |
+        if [ -d "devsoc24-landing/.next" ]; then
+          echo "Build successful"
+        else
+          echo "Build failed"
+          exit 1
+        fi
